
	#[[ CMakeDeps.cmake
	This file was auto-generated by the function update_deps_file() in a
	CMakeLists.txt.	 The function adds this file as a generation dependency
	to ensure that CMake rebuilds the Cache when new source files are added
	to a globbed directory.  When new source files are dropped into a globbed
	directory, this file is updated which triggers a CMakeCache.txt rebuild.
	The file is not actually used in the configuration, build, or compilation.
	]]#
	set(sources include/temporary_file_handler/temporary_file_handler.hpp;src/temporary_file_handler.cpp)
	